### ISSUE TITLE
Prune stale branches

### ISSUE THREAD

**Issue by jakebeal** [SD2E/synbiohub_adapter#57]
This repository has a lot of stale branches.  @nroehner : any objection to me pruning them?

**Comment by tcmitchell** [comment]
Here are the branches and a description of each:

| branch | description |
| ----- | ----- |
| filter_request | pull request #50 |
| fix-resource-uri | pull request #66 |
| large_upload | pull request #10 |
| queryDNA | live branch awaiting pull request |
| refactorTest | Outdated branch from April 2018 with a single line change in a file comment |

**Comment by tcmitchell** [comment]
I have deleted branch `refactorTest`.

The other four branches are still live. I have updated each open pull request to ask the participants what the status is. As these pull requests are handled we will either merge or delete the branches.

I think this issue is complete. Please reopen if there is more to do.
