### ISSUE TITLE
Switch to GitFlow

### ISSUE THREAD

**Issue by jakebeal** [SD2E/synbiohub_adapter#58]
We've been running this unstructured long enough: we need to officially mark a 1.0 release, create a develop branch, and start using GitFlow to manage development

**Comment by zachzundel** [comment]
The GitHub configuration we have for SynBioHub is the following:
 - pushing to `master` is entirely disabled
 - all pull requests must pass CI and have at least 1 approving review

**Comment by tcmitchell** [comment]
This is complete:

* [1.0](https://github.com/SD2E/synbiohub_adapter/releases/tag/v1.0) has been released
* The `develop` branch is now the default branch. All pull requests use `develop` as the base branch by default.
* Git Flow is now [documented](https://github.com/SD2E/synbiohub_adapter/blob/develop/CONTRIBUTING.md) as the workflow model
* Pushing directly to both master and develop is disabled
* Pull requests must pass checks and be up to date in order to be merged
  * I stopped short of requiring review because our most logical reviewers appear to be too busy to keep up with reviews. We can institute this later if the situation changes.
