### ISSUE TITLE
Enhancement request: Clearer feedback on authentication errors

### ISSUE THREAD

**Issue by mwes** [SD2E/synbiohub_adapter#69]
Given that SBHA now checks for an authentication key and a user, but will attempt to run queries anyways if they are not present, I suggest a clearer error message be returned. Essentially an else clause around: 

https://github.com/SD2E/synbiohub_adapter/blob/master/synbiohub_adapter/SynBioHubUtil.py#L179

for the conditions when authentication hasn't been performed yet. Currently the SPARQL query is attempted to be evaluated, but returns some HTML which is not indicative of the actual underlying authentication issue. This was confusing to @danbryce and myself when using code that previously called adapter functions. Thanks!

**Comment by bbartley** [comment]
This is related to SynBioHub issue: https://github.com/SynBioHub/synbiohub/issues/858
Currently Synbiohub redirects back to the home page when a user makes an unauthorized request (hence the HTML you received).  Once the above issue gets resolved, SBHA can simply pass the 401 along to the user.  Until then, we may need to implement some kind of stop gap solution.

**Comment by tcmitchell** [comment]
@mwes Do you have a test case for this? It looks like the underlying SynBioHub issue has been fixed. When authentication fails in `SBOLQuery.login` a `SPARQLWrapper.SPARQLExceptions.Unauthorized` is raised. I don't know if this is a change to the SD2E SynBioHub instance since this issue was created. If you had a test case, I could work with it to verify that authentication errors are properly reported via the raised exception.

I added some unit tests that demonstrate the raised exception as part of PR #89

**Comment by mwes** [comment]
@tcmitchell any test process that omits the "login" step should be sufficient, that's what originally caused the issue with the returned HTML. e.g.
```
        sbh_query = SynBioHubQuery(SD2Constants.SD2_SERVER)
        #omit this
        #sbh_query.login(self.user, self.password)
        design_sets = set(sbh_query.query_design_sets(pretty=True))
```

**Comment by tcmitchell** [comment]
Your description suggests detecting the lack of authentication prior to executing the query. That would be the else clause you suggest.

An alternative is to let the query go through and detect the lack of authentication based on the result from the query. The query returns a byte string of HTML if there is no authentication.

Do you have a preference? My inclination is to go with the latter because it will allow use of synbiohub_adapter on SynBioHub instances that do not require authentication (assuming that's a valid configuration). The code would have to assume that if HTML is received as the result, that the underlying issue was an authentication problem. I don't know if that's a valid assumption.

Both approaches appear to be easy to implement. What are your thoughts?

**Comment by mwes** [comment]
Good point. As we _did_ have a SBH configuration at some point without auth, the latter solution makes sense. If might require some verification against the return HTML, or an assumption, as you note. I'm not sure what SBH's behavior is. Maybe Chris Myers or Zach can confirm?

**Comment by bbartley** [comment]
Hi @tcmitchell 

>The code would have to assume that if HTML is received as the result, that the underlying issue was an authentication problem. I don't know if that's a valid assumption 

I am pretty sure this is a safe assumption.  Otherwise, the endpoints either return RDF/XML or json.

**Comment by tcmitchell** [comment]
@mwes The result without authentication is the SynBioHub home page, exactly. Not indication that there was an authentication issue.

@bbartley Thanks! I'll implement an appropriate check on the results of the query, and if the results look like an HTML bytes string, I'll raise a `SPARQLWrapper.SPARQLExceptions.Unauthorized` exception. That matches the behavior when the `SBOLQuery.login` method fails.
